name: Build and publish Docker image

on:
    push:
        branches: [test/workflow]
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches: [main]

concurrency: production

jobs:
    release:
        name: Tag and create GitHub release
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-24.04-arm
        permissions:
            contents: write
        outputs:
            new_tag: ${{ steps.version.outputs.new_tag }}
            part: ${{ steps.version.outputs.part }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Bump release version and push tag
              id: version
              uses: anothrNick/github-tag-action@1.73.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_API_TAGGING: true
                  WITH_V: false
                  INITIAL_VERSION: 1.0.0
                  DEFAULT_BUMP: patch
                  DEFAULT_BRANCH: main
                  RELEASE_BRANCHES: main

            - name: Create a GitHub release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ steps.version.outputs.new_tag }}
                  name: Release ${{ steps.version.outputs.new_tag }}
                  body: ${{ steps.version.outputs.changelog }}

    publish:
        name: Build and publish Docker image to GitHub Packages
        needs: release
        if: needs.release.outputs.part != 'patch'
        runs-on: ubuntu-24.04-arm
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Authenticate with GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Add tags and labels
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: type=semver,pattern={{version}},value=${{ needs.release.outputs.new_tag }}
                  flavor: latest=auto

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: arm64

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: linux/arm64

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/arm64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ needs.release.outputs.new_tag }}
                      ghcr.io/${{ github.repository }}:latest
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
